### ISSUE TITLE
Navigation Menu is not working

### ISSUE THREAD

**Issue by dukeofsoftware** [shadcn/ui#172]
I copied everyhing from shacdnui but it didn't work
![image](https://user-images.githubusercontent.com/89215036/232235541-bfb6b5e0-87ad-4900-b2a8-6a50919b904e.png)
```
"use client"

import * as React from "react"
import Link from "next/link"

import { cn } from "@/lib/utils"
import {
  NavigationMenu,
  NavigationMenuContent,
  NavigationMenuItem,
  NavigationMenuLink,
  NavigationMenuList,
  NavigationMenuTrigger,
  navigationMenuTriggerStyle,
} from "@/components/ui"

const components: { title: string; href: string; description: string }[] = [
  {
    title: "Alert Dialog",
    href: "/docs/primitives/alert-dialog",
    description:
      "A modal dialog that interrupts the user with important content and expects a response.",
  },
  {
    title: "Hover Card",
    href: "/docs/primitives/hover-card",
    description:
      "For sighted users to preview content available behind a link.",
  },
  {
    title: "Progress",
    href: "/docs/primitives/progress",
    description:
      "Displays an indicator showing the completion progress of a task, typically displayed as a progress bar.",
  },
  {
    title: "Scroll-area",
    href: "/docs/primitives/scroll-area",
    description: "Visually or semantically separates content.",
  },
  {
    title: "Tabs",
    href: "/docs/primitives/tabs",
    description:
      "A set of layered sections of content—known as tab panels—that are displayed one at a time.",
  },
  {
    title: "Tooltip",
    href: "/docs/primitives/tooltip",
    description:
      "A popup that displays information related to an element when the element receives keyboard focus or the mouse hovers over it.",
  },
]

export function Navbar() {
  return (
    <NavigationMenu>
      <NavigationMenuList>
        <NavigationMenuItem>
          <NavigationMenuTrigger>Getting started</NavigationMenuTrigger>
          <NavigationMenuContent>
            <ul className="grid gap-3 p-6 md:w-[400px] lg:w-[500px] lg:grid-cols-[.75fr_1fr]">
              <li className="row-span-3">
                <NavigationMenuLink asChild>
                  <a
                    className="flex h-full w-full select-none flex-col justify-end rounded-md bg-gradient-to-b from-rose-500 to-indigo-700 p-6 no-underline outline-none focus:shadow-md"
                    href="/"
                  >
                    <div className="mt-4 mb-2 text-lg font-medium text-white">
                      shadcn/ui
                    </div>
                    <p className="text-sm leading-tight text-white/90">
                      Beautifully designed components built with Radix UI and
                      Tailwind CSS.
                    </p>
                  </a>
                </NavigationMenuLink>
              </li>
              <ListItem href="/docs" title="Introduction">
                Re-usable components built using Radix UI and Tailwind CSS.
              </ListItem>
              <ListItem href="/docs/installation" title="Installation">
                How to install dependencies and structure your app.
              </ListItem>
              <ListItem href="/docs/primitives/typography" title="Typography">
                Styles for headings, paragraphs, lists...etc
              </ListItem>
            </ul>
          </NavigationMenuContent>
        </NavigationMenuItem>
        <NavigationMenuItem>
          <NavigationMenuTrigger>Components</NavigationMenuTrigger>
          <NavigationMenuContent>
            <ul className="grid w-[400px] gap-3 p-4 md:w-[500px] md:grid-cols-2 lg:w-[600px] ">
              {components.map((component) => (
                <ListItem
                  key={component.title}
                  title={component.title}
                  href={component.href}
                >
                  {component.description}
                </ListItem>
              ))}
            </ul>
          </NavigationMenuContent>
        </NavigationMenuItem>
        <NavigationMenuItem>
          <Link href="/docs" legacyBehavior passHref>
            <NavigationMenuLink className={navigationMenuTriggerStyle()}>
              Documentation
            </NavigationMenuLink>
          </Link>
        </NavigationMenuItem>
      </NavigationMenuList>
    </NavigationMenu>
  )
}

const ListItem = React.forwardRef<
  React.ElementRef<"a">,
  React.ComponentPropsWithoutRef<"a">
>(({ className, title, children, ...props }, ref) => {
  return (
    <li>
      <NavigationMenuLink asChild>
        <a
          ref={ref}
          className={cn(
            "block select-none space-y-1 rounded-md p-3 leading-none no-underline outline-none transition-colors hover:bg-slate-100 focus:bg-slate-100 dark:hover:bg-slate-700 dark:focus:bg-slate-700",
            className
          )}
          {...props}
        >
          <div className="text-sm font-medium leading-none">{title}</div>
          <p className="line-clamp-2 text-sm leading-snug text-slate-500 dark:text-slate-400">
            {children}
          </p>
        </a>
      </NavigationMenuLink>
    </li>
  )
})
ListItem.displayName = "ListItem"

```

**Comment by multiwebinc** [comment]
I'm having the same issue.

**Comment by lloydrichards** [comment]
I'm having a similar issue.  not had much luck apart from making the NavigationMenuContent centered and set to an extra large width.  One thing i noticed though is that there are several tailwind classes which don't actually exist in the `navigation-menu.tsx`. 

- line 33: `group`
- line 53: `group`
- line 89: `origin-top-center`

Maybe these are supposed to be doing something i'm unaware of 🤷

**Comment by qualiky** [comment]
I don't think this has been fixed. Is it working?

**Comment by multiwebinc** [comment]
It looks like this is an issue with Radix. See: https://github.com/radix-ui/primitives/issues/1462

**Comment by guepejuang** [comment]
same issue
![image](https://github.com/shadcn/ui/assets/42382490/dc8b4302-380c-4821-ac8e-4ac899be12a4)

**Comment by gabrieloureiro** [comment]
up

**Comment by Josevictor2** [comment]
up

**Comment by AdiRishi** [comment]
Hey @shadcn the issue is definitely still there, ran into it yesterday.
Here is a minimal reproduction repository - https://github.com/AdiRishi/shadcn-navbar-bug-demo . The repository code basically copied the example on the docs website and added many more links to the navbar to highlight the bug.

Quick video to demo the issue
![shadcn-navbar-bug-demo](https://github.com/shadcn-ui/ui/assets/8351234/6b5e7fc3-82e3-42a2-baf6-415b1e8c81b9)

Hope this helps, really looking forward to a fix.

**Comment by tharsis-soares** [comment]
I could change little bit changing 
"const NavigationMenuViewport = React.forwardRef<
  React.ElementRef<typeof NavigationMenuPrimitive.Viewport>,
  React.ComponentPropsWithoutRef<typeof NavigationMenuPrimitive.Viewport>
>(({ className, ...props }, ref) => (
  <div className={cn("absolute "**left-60** top-full flex justify-center")}>
    <NavigationMenuPrimitive.Viewport
      className={cn(
        "relative mt-1.5 h-[var(--radix-navigation-menu-viewport-height)] w-full overflow-hidden rounded-md border bg-popover text-popover-foreground shadow-lg data-[state=open]:animate-in data-[state=closed]:animate-out data-[state=closed]:zoom-out-95 data-[state=open]:zoom-in-90 md:w-[var(--radix-navigation-menu-viewport-width)]",
        className
      )}
      ref={ref}
      {...props}
    />
  </div>
))"

  <div className={cn("absolute "**left-60** top-full flex justify-center")}> was left-0, but doesnt fit perfect

**Comment by Lauro235** [comment]
I've noticed the same thing! Would love this to be updated.

**Comment by beinawair** [comment]
Maybe this issue closed but for future references, 
the fix is when you are creating menu, make sure to include `<NavigationMenuItem>` (because I made this mistake before)

for example, 

instead of this:
`<NavigationMenuItem>
   <NavigationMenuTrigger>Getting started</NavigationMenuTrigger>
   <NavigationMenuContent>
      ...
   </NavigationMenuContent>
   <NavigationMenuContent>
      ...
   </NavigationMenuContent>
</NavigationMenuItem>`

do this:
`<NavigationMenuItem>
   <NavigationMenuTrigger>Getting started</NavigationMenuTrigger>
   <NavigationMenuContent>
      ...
   </NavigationMenuContent>
</NavigationMenuItem>
<NavigationMenuItem>
   <NavigationMenuTrigger>What's next</NavigationMenuTrigger>
   <NavigationMenuContent>
      ...
   </NavigationMenuContent>
</NavigationMenuItem>
`

**Comment by volumbe** [comment]
I am still facing the same issue with the example code from https://ui.shadcn.com/docs/components/navigation-menu#examples.

**Comment by CyrusVorwald** [comment]
I am also facing this issue.

**Comment by zhefciad** [comment]
Still no fix?

**Comment by leandroruel** [comment]
hmmm.... i just can't make my trigger make the chevron ork, like... the code is there... just don't work... for some reason.

**Comment by LasseSiebert-WW** [comment]
Issue still not fixed

**Comment by leandroruel** [comment]
> hmmm.... i just can't make my trigger make the chevron work, like... the code is there... just don't work... for some reason.

i fixed my problem. had to move the components folder to inside my app/ folder then i changed a bit of CSS
https://gist.github.com/leandroruel/e1775f4348a5295aa4d5195fd5c2bbdb

**Comment by maxpaleo** [comment]
> @vicky002 do you have reproducible copy? I remember I pushed a fix for this.

This still doesn't seem to have been fixed lol; there's quite a few issues on the topic. It might be worth considering just simplying the NavigationMenu to make it more consistent

**Comment by lassesbrt** [comment]
I was able to work around the issue by applying a custom translation offset to the NavigationMenuViewport.vue. It's not the cleanest solution, but it has proven to work very well for us in production.

## Here is how I did it exactly

### NavigationMenu.vue
I make use of the radix-* attributes applied to each NavigationMenuItem. These attributes are applied automatically by radix-vue and are passed to NavigationMenu.vue when hovering over any item from the navbar.

The id is passed in the value property of the forwarded constant inside NavigationMenu.vue:
`const forwarded = useForwardPropsEmits(delegatedProps, emits)`

I think the value is passed to the NavigationMenuViewport by default. But if not, modify your NavigationMenu.vue to pass the :value prop to the NavigationMenuViewport:
`<NavigationMenuRoot
    v-bind="forwarded"
    :class="cn('relative z-10 flex max-w-max flex-1 items-center justify-center', props.class)"
  >
    <slot />
    <NavigationMenuViewport :value="forwarded?.modelValue" :opacity="forwarded?.modelValue ? true : false" />
  </NavigationMenuRoot>`

### NavigatonMenuViewport.vue
You can then move on to the NavigationMenuViewport.vue. I watch the value from forwardedProps (to detect changes to the radix id, thus hover on a menu item).

The watcher does a couple of things:

1. Check if the radix id is empty
If yes, disable the transition. Not doing this will cause the opened menu dropdown to slide all the way to the left (0px) while it closes, which does not make for a nice effect. I wait for the closing animation to finish before resetting the position to 0.

2. Get the NavigationMenuItem index in the navbar
The radix ids are usually applied in consecutive order to the menu items and should stay the same. However, the ids may change if your header remounts. We have a settings page which does not show the header. Therefore, it is necessary to calculate the index of the menu item at runtime to avoid issues where the menu dropdown is placed in the wrong position. The findElementIndexByIdSuffix method does exactly that.

3. Change the offset to your liking
We have a fixed multiplier of 50, which has proven to work well for us, but it may be different for you. Change the multiplier to your liking by modifying this line:
`:style="{ transform: `translateX(${selectedDropdown * 50}px)` }"`

*This is the full code for our NavigationMenuViewport.vue*

`<script setup lang="ts">
import { cn } from '@/lib/utils';
import { NavigationMenuViewport, useForwardProps, type NavigationMenuViewportProps } from 'radix-vue';
import { computed, nextTick, ref, watch, type HTMLAttributes } from 'vue';

const props = defineProps<NavigationMenuViewportProps & { class?: HTMLAttributes['class']; opacity: boolean; value: string }>();

const delegatedProps = computed(() => {
  const { class: _, ...delegated } = props;

  return delegated;
});

const forwardedProps = useForwardProps(delegatedProps);

const selectedDropdown = ref(0);
const enableTransition = ref(false);

function findElementIndexByIdSuffix(suffix: string) {
  const element = document.querySelector(`[id$="${suffix}"]`);

  if (!element) {
    console.error('No element found with the specified ID suffix');
    return -1;
  }

  const menuItem = element.parentElement;

  if (!menuItem) {
    console.error('The found element has no menu item');
    return -1;
  }

  const parent = menuItem.parentElement;

  if (!parent) {
    console.error('The found element has no parent');
    return -1;
  }

  const children = Array.from(parent.children);

  const index = children.indexOf(menuItem);

  return index;
}

watch(
  computed(() => forwardedProps.value?.value),
  value => {
    if (!value?.length) {
      enableTransition.value = false;
      setTimeout(() => {
        selectedDropdown.value = 0;
      }, 150);
      return;
    }

    selectedDropdown.value = findElementIndexByIdSuffix(value) || 0;

    nextTick(() => {
      enableTransition.value = true;
    });
  }
);
</script>

<template>
  <div
    :class="[props.opacity ? 'opacity-100' : 'opacity-0', enableTransition ? 'transition' : 'transition-opacity']"
    :style="{ transform: `translateX(${selectedDropdown * 50}px)` }"
    :data-id="props.value"
    class="transform absolute -left-6 top-full flex justify-center w-header-menu"
  >
    <NavigationMenuViewport
      v-bind="forwardedProps"
      :class="
        cn(
          'origin-top-center relative mt-1.5 h-[--radix-navigation-menu-viewport-height] w-full overflow-hidden rounded-2xl border bg-popover text-popover-foreground shadow-lg data-[state=open]:animate-in data-[state=closed]:animate-out data-[state=closed]:zoom-out-95 data-[state=open]:zoom-in-90 md:w-[--radix-navigation-menu-viewport-width]',
          'z-100 relative',
          props.class
        )
      "
    />
  </div>
</template>
`

Hope this helps some of you to work around the ever lasting bugs of this otherwise very good looking component.

**Comment by grepsoft** [comment]
the ListItem just disappeared. If you look the example for NavigationMenu on the ShadcnUI site they are using ListItem but there is no import on the top.
has it been removed?

**Comment by nkorent** [comment]
this is still not working, has this been fixed?
I have also found the same issue as grepsoft...

**Comment by firstcomeuropeag** [comment]
push.

**Comment by maxpaleo** [comment]
up

**Comment by softwarenomad** [comment]
This is still an issue. A temporary work around I found while waiting for a fix is to disable the viewport on the `NavigationMenu` and adding the z-index manually:
```
            <NavigationMenu className="z-1" viewport={false}>

```

Would also like to see a fix for this and the NavigationMenuIndicator not being aligned to the opened menu option.

**Comment by yoonthegoon** [comment]
> This is still an issue. A temporary work around I found while waiting for a fix is to disable the viewport on the `NavigationMenu` and adding the z-index manually:
> 
> ```
>             <NavigationMenu className="z-1" viewport={false}>
> ```
> 
> Would also like to see a fix for this and the NavigationMenuIndicator not being aligned to the opened menu option.

This worked for me. To add to this fix, you'll want to have

```tsx
<NavigationMenuContent className="absolute">
```

So that the navigation menu content appears below the trigger for smaller screens.

With `className="absolute"`: 

<img width="315" alt="Image" src="https://github.com/user-attachments/assets/792a9a21-7cfd-4b31-9ae3-ae1d553dd059" />

Without:

<img width="422" alt="Image" src="https://github.com/user-attachments/assets/564772ef-cdb5-4435-b661-4e17280d513f" />

**Comment by jatindecoded** [comment]
adding viewport={false} to the NavigationMenu did the job for me. you can use this as a workaround.

**Comment by SuperRonanCraft** [comment]
> adding viewport={false} to the NavigationMenu did the job for me. you can use this as a workaround.

How were you able to add viewport={false} I literally get an error saying this field doesn't exist

<img width="1117" height="196" alt="Image" src="https://github.com/user-attachments/assets/ed810d70-6268-4373-8292-170fb8ba63b2" />

**Comment by coffee-sprinkler** [comment]
still not fixed

**Comment by mushkirmohamedtitum** [comment]
Still not
